addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.1")
addSbtPlugin("com.mintbeans"    % "sbt-ecr"             % "0.14.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.2.0")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "0.14.8")
addCompilerPlugin("com.olegpy"  %% "better-monadic-for" % "0.3.1")
